theme: minima
title: random ramblings of robust resonance
author: Paul Lipsitz

# Authors
authors:
  Paul:
    name: Paul
    display_name: Paul
    email: paul.lipsitz@gmail.com
    github: https://github.com/wrongusernameyetagain
    description: "I used to have more fun when I wasn't aware I was having fun"
